---
title: "Analisis_Multivariadoo"
output: html_notebook
---

```{r}
redwine <- read.csv("https://bit.ly/2DdpG9E", header = T)
```
```{r}
str(redwine)
summary(redwine)
```
```{r}
cov(redwine)
cor(redwine)
cor(redwine[,c("ï..fixed.acidity","citric.acid","pH")])
```


```{r, fig.width=10, fig.height=10}
plot(redwine)
```

```{r}
plot(redwine$ï..fixed.acidity ~ redwine$citric.acid)
```

```{r}
vino6<-subset(redwine,quality==6)
Boxplot(vino6$ï..fixed.acidity)
abline(h=13,col=6)
vino61<-filter(vino6,ï..fixed.acidity<12)
Boxplot(vino61$ï..fixed.acidity)
```

```{r}
boxplot(vino61$pH)
quantile(vino61$pH)
abline(h=3.7,col=6)

```

```{r}
vino62<-filter(vino61, pH<3.7)
boxplot(vino62$pH)
```

```{r}
qqnorm(vino62[,"pH"],main = "PH")
qqline(vino62[,"pH"])
```

```{r}
x<-vino62$pH

plotnormal<-function(x)
{media<-mean(x)
desv<-sd(x)
hist(x, freq = F)
curve(dnorm(x,media,desv),add = T,col=2)    
     abline(v=media,col=2)
}
```

```{r}
plotnormal(x)
```




```{r}
library(normtest)
library(nortest)
ad.test(x)
```
```{r}
jb.norm.test(x)
```
















