```{r}
v<-c(1,3,5,7)
length(v)
```


```{r}
v<-c("uno","tres","cinco","siete")
length(v)
v<-c(TRUE,FALSE)     
```

```{r}
b<-c(1,2,3,4)
b
length(b)
names(b)<-c("uno","dos","tres","cuatro")
b
```
```{r}
j<-c(2,3,5,7,11,13,17)
length(j)
j[c(2,6,5)]

```
```{r}
indice<-c(1,5,8)
j[indice]
```
```{r}
v <- c(5, 10, 15, 20) 
w <- c(3, 6, 9, 12)
rbind(v,w)
```
```{r}
x<-c(1,2,3,4)
m<-rbind(v,w,x) 
m
```
```{r}
row.names(m)<-c("benjamin","jonas","condori")
colnames(m)<-c("jennifer","rocio","flores","Jenni")
m
```

```{r}
v <- c(10, 11, 12)
w <- c(13, 14, 15)
x <- c(16, 17, 18)
m<-cbind(v,w,x)
m
m[2,-3]
```
```{r}
filas<-c(1,3)
columnas<-c(2,3)
rbind(filas,columnas)

```

```{r}
Costo <- c(7.3, 9.5, 8.6, 11.3, 6.7, 7.7)
Mes <- c("Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio")
Excedente <- c(FALSE, TRUE, FALSE, TRUE, FALSE, FALSE)
df <- data.frame(Costo, Mes, Excedente) 
df
```
```{r}
write.csv(df,"costroprouccion.csv",row.names = FALSE)
```

```{r}
df<-read.csv("costroprouccion.csv")
df$Costo
```
```{r}
library(dplyr)
filter(df,Mes=="Abril")
```




















